name: ftc_stocks
description: "Stocks handle of FTC."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Widgets Libs
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  intl: ^0.20.2
  google_fonts: ^7.0.2
  dropdown_search: ^6.0.2
  textfield_tags: ^3.0.1
  responsive_sizer: ^3.3.1
  font_awesome_flutter: ^10.12.0
  flutter_native_splash: ^2.4.7

  # State Management Lib
  get: ^4.7.3

  # Device & App Info Libs
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0

  # Network Libs
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  json_serializable: ^6.11.4
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2

  # File Libs
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  whatsapp_share2: ^2.1.1

  # Firebase Libs
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  awesome_notifications_core: ^0.10.1
  awesome_notifications: ^0.10.1

  # Syncfusion Libs
  syncfusion_flutter_core: ^32.1.23
  syncfusion_flutter_pdfviewer: ^32.1.23

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_native_splash:
  image: assets/images/native_splash_image.png
  color: "#FDF8F8"
  android_12:
    image: assets/images/native_splash_image.png
    color: "#FDF8F8"